version: '3'

services:

  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    environment:
      APP_ENV: prod
      DATABASE_URL: pgsql://domainmod:password@host.docker.internal/domainmod?serverVersion=12.3
    volumes:
      - phpsocket:/var/run/php

  nginx:
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    volumes:
      - phpsocket:/var/run/php
    ports:
      - 8001:80

volumes:
  phpsocket: