<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20200727205411 extends AbstractMigration
{
    public function getDescription() : string
    {
        return 'Initial database schema';
    }

    public function up(Schema $schema) : void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() !== 'postgresql', 'Migration can only be executed safely on \'postgresql\'.');

        $this->addSql('CREATE TABLE domain (id UUID NOT NULL, owner_id UUID DEFAULT NULL, registrar_id UUID DEFAULT NULL, account_id UUID DEFAULT NULL, category_id UUID DEFAULT NULL, fee_id UUID DEFAULT NULL, dns_id UUID DEFAULT NULL, ip_id UUID DEFAULT NULL, hosting_id UUID DEFAULT NULL, creation_type_id UUID DEFAULT NULL, name VARCHAR(255) NOT NULL, tld VARCHAR(50) NOT NULL, expiry_date DATE NOT NULL, total_cost DOUBLE PRECISION NOT NULL, function VARCHAR(255) DEFAULT NULL, notes TEXT DEFAULT NULL, autorenew BOOLEAN NOT NULL, privacy BOOLEAN NOT NULL, transfer_lock BOOLEAN DEFAULT \'false\' NOT NULL, status VARCHAR(2) DEFAULT \'1\' NOT NULL, fee_fixed BOOLEAN NOT NULL, created_by VARCHAR(255) DEFAULT NULL, updated_by VARCHAR(255) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_A7A91E0B7E3C61F9 ON domain (owner_id)');
        $this->addSql('CREATE INDEX IDX_A7A91E0BD1AA2FC1 ON domain (registrar_id)');
        $this->addSql('CREATE INDEX IDX_A7A91E0B9B6B5FBA ON domain (account_id)');
        $this->addSql('CREATE INDEX IDX_A7A91E0B12469DE2 ON domain (category_id)');
        $this->addSql('CREATE INDEX IDX_A7A91E0BAB45AECA ON domain (fee_id)');
        $this->addSql('CREATE INDEX IDX_A7A91E0BE42F3693 ON domain (dns_id)');
        $this->addSql('CREATE INDEX IDX_A7A91E0BA03F5E9F ON domain (ip_id)');
        $this->addSql('CREATE INDEX IDX_A7A91E0BAE9044EA ON domain (hosting_id)');
        $this->addSql('CREATE INDEX IDX_A7A91E0BE54D5EF8 ON domain (creation_type_id)');
        $this->addSql('CREATE INDEX domain_name_idx ON domain (name)');
        $this->addSql('CREATE TABLE category (id UUID NOT NULL, creation_type_id UUID DEFAULT NULL, name VARCHAR(150) NOT NULL, stakeholder VARCHAR(100) DEFAULT NULL, notes TEXT DEFAULT NULL, created_by VARCHAR(255) DEFAULT NULL, updated_by VARCHAR(255) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_64C19C1E54D5EF8 ON category (creation_type_id)');
        $this->addSql('CREATE TABLE segment (id UUID NOT NULL, creation_type_id UUID DEFAULT NULL, name VARCHAR(35) NOT NULL, description TEXT DEFAULT NULL, segment TEXT NOT NULL, number_of_domains INT NOT NULL, notes TEXT DEFAULT NULL, created_by VARCHAR(255) DEFAULT NULL, updated_by VARCHAR(255) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_1881F565E54D5EF8 ON segment (creation_type_id)');
        $this->addSql('CREATE TABLE registrar_account (id UUID NOT NULL, owner_id UUID DEFAULT NULL, registrar_id UUID DEFAULT NULL, api_ip_id UUID DEFAULT NULL, creation_type_id UUID DEFAULT NULL, email_address VARCHAR(100) DEFAULT NULL, username VARCHAR(100) DEFAULT NULL, password VARCHAR(255) DEFAULT NULL, reseller BOOLEAN NOT NULL, reseller_id VARCHAR(100) DEFAULT NULL, api_app_name VARCHAR(255) DEFAULT NULL, api_key VARCHAR(255) DEFAULT NULL, api_secret VARCHAR(255) DEFAULT NULL, api_token TEXT DEFAULT NULL, notes TEXT DEFAULT NULL, created_by VARCHAR(255) DEFAULT NULL, updated_by VARCHAR(255) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_CBDB68567E3C61F9 ON registrar_account (owner_id)');
        $this->addSql('CREATE INDEX IDX_CBDB6856D1AA2FC1 ON registrar_account (registrar_id)');
        $this->addSql('CREATE INDEX IDX_CBDB685684AA0A4F ON registrar_account (api_ip_id)');
        $this->addSql('CREATE INDEX IDX_CBDB6856E54D5EF8 ON registrar_account (creation_type_id)');
        $this->addSql('CREATE TABLE owner (id UUID NOT NULL, creation_type_id UUID DEFAULT NULL, name VARCHAR(100) NOT NULL, notes TEXT DEFAULT NULL, created_by VARCHAR(255) DEFAULT NULL, updated_by VARCHAR(255) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_CF60E67CE54D5EF8 ON owner (creation_type_id)');
        $this->addSql('CREATE TABLE registrar (id UUID NOT NULL, api_registrar_id UUID DEFAULT NULL, creation_type_id UUID DEFAULT NULL, name VARCHAR(100) NOT NULL, url VARCHAR(100) DEFAULT NULL, notes TEXT DEFAULT NULL, created_by VARCHAR(255) DEFAULT NULL, updated_by VARCHAR(255) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_E0A26C7DBC0F66C ON registrar (api_registrar_id)');
        $this->addSql('CREATE INDEX IDX_E0A26C7E54D5EF8 ON registrar (creation_type_id)');
        $this->addSql('CREATE TABLE dns (id UUID NOT NULL, creation_type_id UUID DEFAULT NULL, name VARCHAR(255) NOT NULL, dns1 VARCHAR(255) NOT NULL, dns2 VARCHAR(255) NOT NULL, dns3 VARCHAR(255) DEFAULT NULL, dns4 VARCHAR(255) DEFAULT NULL, dns5 VARCHAR(255) DEFAULT NULL, dns6 VARCHAR(255) DEFAULT NULL, dns7 VARCHAR(255) DEFAULT NULL, dns8 VARCHAR(255) DEFAULT NULL, dns9 VARCHAR(255) DEFAULT NULL, dns10 VARCHAR(255) DEFAULT NULL, ip1 VARCHAR(45) DEFAULT NULL, ip2 VARCHAR(45) DEFAULT NULL, ip3 VARCHAR(45) DEFAULT NULL, ip4 VARCHAR(45) DEFAULT NULL, ip5 VARCHAR(45) DEFAULT NULL, ip6 VARCHAR(45) DEFAULT NULL, ip7 VARCHAR(45) DEFAULT NULL, ip8 VARCHAR(45) DEFAULT NULL, ip9 VARCHAR(45) DEFAULT NULL, ip10 VARCHAR(45) DEFAULT NULL, notes TEXT DEFAULT NULL, number_of_servers INT NOT NULL, created_by VARCHAR(255) DEFAULT NULL, updated_by VARCHAR(255) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_82EDDC41E54D5EF8 ON dns (creation_type_id)');
        $this->addSql('CREATE TABLE domain_queue_history (id UUID NOT NULL, api_registrar_id UUID DEFAULT NULL, domain_id UUID DEFAULT NULL, owner_id UUID DEFAULT NULL, registrar_id UUID DEFAULT NULL, account_id UUID DEFAULT NULL, category_id UUID DEFAULT NULL, dns_id UUID DEFAULT NULL, ip_address_id UUID DEFAULT NULL, hosting_id UUID DEFAULT NULL, domain_name VARCHAR(255) NOT NULL, tld VARCHAR(50) NOT NULL, expiry_date DATE NOT NULL, auto_renew BOOLEAN NOT NULL, privacy BOOLEAN NOT NULL, already_in_domains BOOLEAN NOT NULL, already_in_queue BOOLEAN NOT NULL, created_by VARCHAR(255) DEFAULT NULL, updated_by VARCHAR(255) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_56A81B9EDBC0F66C ON domain_queue_history (api_registrar_id)');
        $this->addSql('CREATE INDEX IDX_56A81B9E115F0EE5 ON domain_queue_history (domain_id)');
        $this->addSql('CREATE INDEX IDX_56A81B9E7E3C61F9 ON domain_queue_history (owner_id)');
        $this->addSql('CREATE INDEX IDX_56A81B9ED1AA2FC1 ON domain_queue_history (registrar_id)');
        $this->addSql('CREATE INDEX IDX_56A81B9E9B6B5FBA ON domain_queue_history (account_id)');
        $this->addSql('CREATE INDEX IDX_56A81B9E12469DE2 ON domain_queue_history (category_id)');
        $this->addSql('CREATE INDEX IDX_56A81B9EE42F3693 ON domain_queue_history (dns_id)');
        $this->addSql('CREATE INDEX IDX_56A81B9E5F23F921 ON domain_queue_history (ip_address_id)');
        $this->addSql('CREATE INDEX IDX_56A81B9EAE9044EA ON domain_queue_history (hosting_id)');
        $this->addSql('CREATE TABLE custom_field_type (id UUID NOT NULL, name VARCHAR(150) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE fee (id UUID NOT NULL, registrar_id UUID DEFAULT NULL, currency_id UUID DEFAULT NULL, tld VARCHAR(50) NOT NULL, initial_fee DOUBLE PRECISION NOT NULL, renewal_fee DOUBLE PRECISION NOT NULL, transfer_fee DOUBLE PRECISION NOT NULL, privacy_fee DOUBLE PRECISION NOT NULL, misc_fee DOUBLE PRECISION NOT NULL, fee_fixed BOOLEAN NOT NULL, created_by VARCHAR(255) DEFAULT NULL, updated_by VARCHAR(255) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_964964B5D1AA2FC1 ON fee (registrar_id)');
        $this->addSql('CREATE INDEX IDX_964964B538248176 ON fee (currency_id)');
        $this->addSql('CREATE INDEX IDX_964964B52F2E9874D1AA2FC1 ON fee (tld, registrar_id)');
        $this->addSql('CREATE TABLE user_setting (id UUID NOT NULL, user_id UUID DEFAULT NULL, default_category_domains_id UUID DEFAULT NULL, default_category_ssl_id UUID DEFAULT NULL, default_dns_id UUID DEFAULT NULL, default_host_id UUID DEFAULT NULL, default_ip_address_domains_id UUID DEFAULT NULL, default_ip_address_ssl_id UUID DEFAULT NULL, default_owner_domains_id UUID DEFAULT NULL, default_owner_ssl_id UUID DEFAULT NULL, default_registrar_id UUID DEFAULT NULL, default_registrar_account_id UUID DEFAULT NULL, default_ssl_provider_account_id UUID DEFAULT NULL, default_ssl_type_id UUID DEFAULT NULL, default_ssl_provider_id UUID DEFAULT NULL, default_currency VARCHAR(3) NOT NULL, default_timezone VARCHAR(50) DEFAULT \'\'\'Canada/Pacific\'\'\' NOT NULL, expiration_emails BOOLEAN NOT NULL, number_of_domains INT DEFAULT 50 NOT NULL, number_of_ssl_certs INT DEFAULT 50 NOT NULL, display_domain_owner BOOLEAN NOT NULL, display_domain_registrar BOOLEAN NOT NULL, display_domain_account BOOLEAN DEFAULT \'true\' NOT NULL, display_domain_expiry_date BOOLEAN DEFAULT \'true\' NOT NULL, display_domain_category BOOLEAN DEFAULT \'true\' NOT NULL, display_domain_dns BOOLEAN DEFAULT \'true\' NOT NULL, display_domain_host BOOLEAN NOT NULL, display_domain_ip BOOLEAN NOT NULL, display_domain_tld BOOLEAN DEFAULT \'true\' NOT NULL, display_domain_fee BOOLEAN DEFAULT \'true\' NOT NULL, display_ssl_owner BOOLEAN DEFAULT \'true\' NOT NULL, display_ssl_provider BOOLEAN NOT NULL, display_ssl_account BOOLEAN DEFAULT \'true\' NOT NULL, display_ssl_domain BOOLEAN DEFAULT \'true\' NOT NULL, display_ssl_type BOOLEAN DEFAULT \'true\' NOT NULL, display_ssl_expiry_date BOOLEAN DEFAULT \'true\' NOT NULL, display_ssl_ip BOOLEAN NOT NULL, display_ssl_category BOOLEAN NOT NULL, display_ssl_fee BOOLEAN NOT NULL, display_inactive_assets BOOLEAN DEFAULT \'true\' NOT NULL, display_dw_intro_page BOOLEAN DEFAULT \'true\' NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_C779A692A76ED395 ON user_setting (user_id)');
        $this->addSql('CREATE INDEX IDX_C779A692B8C24FFF ON user_setting (default_category_domains_id)');
        $this->addSql('CREATE INDEX IDX_C779A692FD4872ED ON user_setting (default_category_ssl_id)');
        $this->addSql('CREATE INDEX IDX_C779A69237E3DC0 ON user_setting (default_dns_id)');
        $this->addSql('CREATE INDEX IDX_C779A692ED3D80C0 ON user_setting (default_host_id)');
        $this->addSql('CREATE INDEX IDX_C779A6925A593FA4 ON user_setting (default_ip_address_domains_id)');
        $this->addSql('CREATE INDEX IDX_C779A692AB5F6375 ON user_setting (default_ip_address_ssl_id)');
        $this->addSql('CREATE INDEX IDX_C779A692EA97A5CE ON user_setting (default_owner_domains_id)');
        $this->addSql('CREATE INDEX IDX_C779A692EDDAD9BE ON user_setting (default_owner_ssl_id)');
        $this->addSql('CREATE INDEX IDX_C779A692F37CCA6B ON user_setting (default_registrar_id)');
        $this->addSql('CREATE INDEX IDX_C779A692A7268CA8 ON user_setting (default_registrar_account_id)');
        $this->addSql('CREATE INDEX IDX_C779A69257476562 ON user_setting (default_ssl_provider_account_id)');
        $this->addSql('CREATE INDEX IDX_C779A692ABBB6804 ON user_setting (default_ssl_type_id)');
        $this->addSql('CREATE INDEX IDX_C779A69275D832EE ON user_setting (default_ssl_provider_id)');
        $this->addSql('CREATE TABLE creation_type (id UUID NOT NULL, name VARCHAR(255) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE api_registrar (id UUID NOT NULL, name VARCHAR(255) NOT NULL, req_account_username BOOLEAN NOT NULL, req_account_password BOOLEAN NOT NULL, req_reseller_id BOOLEAN NOT NULL, req_api_app_name BOOLEAN NOT NULL, req_api_key BOOLEAN NOT NULL, req_api_secret BOOLEAN NOT NULL, req_api_token BOOLEAN DEFAULT \'false\' NOT NULL, req_ip_address BOOLEAN NOT NULL, lists_domains BOOLEAN NOT NULL, ret_expiry_date BOOLEAN NOT NULL, ret_dns_servers BOOLEAN NOT NULL, ret_privacy_status BOOLEAN NOT NULL, ret_transfer_lock BOOLEAN DEFAULT \'false\' NOT NULL, ret_autorenewal_status BOOLEAN NOT NULL, notes TEXT DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE ssl_account (id UUID NOT NULL, owner_id UUID DEFAULT NULL, ssl_provider_id UUID DEFAULT NULL, creation_type_id UUID DEFAULT NULL, email_address VARCHAR(100) DEFAULT NULL, username VARCHAR(100) NOT NULL, password VARCHAR(255) DEFAULT NULL, reseller BOOLEAN NOT NULL, reseller_id VARCHAR(100) DEFAULT NULL, notes TEXT DEFAULT NULL, created_by VARCHAR(255) DEFAULT NULL, updated_by VARCHAR(255) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_C732A1857E3C61F9 ON ssl_account (owner_id)');
        $this->addSql('CREATE INDEX IDX_C732A185ED8E9A32 ON ssl_account (ssl_provider_id)');
        $this->addSql('CREATE INDEX IDX_C732A185E54D5EF8 ON ssl_account (creation_type_id)');
        $this->addSql('CREATE TABLE users (id UUID NOT NULL, creation_type_id UUID DEFAULT NULL, first_name VARCHAR(50) NOT NULL, last_name VARCHAR(50) NOT NULL, username VARCHAR(30) NOT NULL, email_address VARCHAR(100) NOT NULL, password VARCHAR(255) NOT NULL, new_password BOOLEAN DEFAULT \'true\' NOT NULL, admin BOOLEAN NOT NULL, read_only BOOLEAN DEFAULT \'true\' NOT NULL, active BOOLEAN DEFAULT \'true\' NOT NULL, number_of_logins INT NOT NULL, last_login TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, created_by VARCHAR(255) DEFAULT NULL, updated_by VARCHAR(255) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_1483A5E9E54D5EF8 ON users (creation_type_id)');
        $this->addSql('CREATE TABLE ssl_cert (id UUID NOT NULL, owner_id UUID DEFAULT NULL, ssl_provider_id UUID DEFAULT NULL, account_id UUID DEFAULT NULL, domain_id UUID DEFAULT NULL, type_id UUID DEFAULT NULL, ip_id UUID DEFAULT NULL, category_id UUID DEFAULT NULL, fee_id UUID DEFAULT NULL, creation_type_id UUID DEFAULT NULL, name VARCHAR(100) NOT NULL, expiry_date DATE NOT NULL, total_cost NUMERIC(10, 2) NOT NULL, notes TEXT DEFAULT NULL, status VARCHAR(2) DEFAULT \'1\' NOT NULL, thumbprint VARCHAR(255) DEFAULT NULL, fee_fixed BOOLEAN NOT NULL, created_by VARCHAR(255) DEFAULT NULL, updated_by VARCHAR(255) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_72E6EBE07E3C61F9 ON ssl_cert (owner_id)');
        $this->addSql('CREATE INDEX IDX_72E6EBE0ED8E9A32 ON ssl_cert (ssl_provider_id)');
        $this->addSql('CREATE INDEX IDX_72E6EBE09B6B5FBA ON ssl_cert (account_id)');
        $this->addSql('CREATE INDEX IDX_72E6EBE0115F0EE5 ON ssl_cert (domain_id)');
        $this->addSql('CREATE INDEX IDX_72E6EBE0C54C8C93 ON ssl_cert (type_id)');
        $this->addSql('CREATE INDEX IDX_72E6EBE0A03F5E9F ON ssl_cert (ip_id)');
        $this->addSql('CREATE INDEX IDX_72E6EBE012469DE2 ON ssl_cert (category_id)');
        $this->addSql('CREATE INDEX IDX_72E6EBE0AB45AECA ON ssl_cert (fee_id)');
        $this->addSql('CREATE INDEX IDX_72E6EBE0E54D5EF8 ON ssl_cert (creation_type_id)');
        $this->addSql('CREATE TABLE ssl_cert_type (id UUID NOT NULL, creation_type_id UUID DEFAULT NULL, type VARCHAR(100) NOT NULL, notes TEXT DEFAULT NULL, created_by VARCHAR(255) DEFAULT NULL, updated_by VARCHAR(255) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_483791B2E54D5EF8 ON ssl_cert_type (creation_type_id)');
        $this->addSql('CREATE TABLE domain_queue_list_history (id UUID NOT NULL, api_registrar_id UUID DEFAULT NULL, owner_id UUID DEFAULT NULL, registrar_id UUID DEFAULT NULL, account_id UUID DEFAULT NULL, domain_count INT NOT NULL, created_by VARCHAR(255) DEFAULT NULL, updated_by VARCHAR(255) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_7F4112C4DBC0F66C ON domain_queue_list_history (api_registrar_id)');
        $this->addSql('CREATE INDEX IDX_7F4112C47E3C61F9 ON domain_queue_list_history (owner_id)');
        $this->addSql('CREATE INDEX IDX_7F4112C4D1AA2FC1 ON domain_queue_list_history (registrar_id)');
        $this->addSql('CREATE INDEX IDX_7F4112C49B6B5FBA ON domain_queue_list_history (account_id)');
        $this->addSql('CREATE TABLE ip_address (id UUID NOT NULL, creation_type_id UUID DEFAULT NULL, name VARCHAR(100) NOT NULL, ip VARCHAR(45) NOT NULL, rdns VARCHAR(255) DEFAULT NULL, notes TEXT DEFAULT NULL, created_by VARCHAR(255) DEFAULT NULL, updated_by VARCHAR(255) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_22FFD58CE54D5EF8 ON ip_address (creation_type_id)');
        $this->addSql('CREATE TABLE scheduler (id UUID NOT NULL, name VARCHAR(100) NOT NULL, slug VARCHAR(50) DEFAULT NULL, description TEXT DEFAULT NULL, interval VARCHAR(50) DEFAULT \'\'\'Daily\'\'\' NOT NULL, expression VARCHAR(20) NOT NULL, last_run TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, last_duration VARCHAR(255) DEFAULT NULL, next_run TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, sort_order INT DEFAULT 1 NOT NULL, is_running BOOLEAN NOT NULL, active BOOLEAN DEFAULT \'true\' NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE ssl_fee (id UUID NOT NULL, ssl_provider_id UUID DEFAULT NULL, type_id UUID DEFAULT NULL, currency_id UUID DEFAULT NULL, initial_fee NUMERIC(10, 2) NOT NULL, renewal_fee NUMERIC(10, 2) NOT NULL, misc_fee NUMERIC(10, 2) NOT NULL, fee_fixed BOOLEAN NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_6BFE52B8ED8E9A32 ON ssl_fee (ssl_provider_id)');
        $this->addSql('CREATE INDEX IDX_6BFE52B8C54C8C93 ON ssl_fee (type_id)');
        $this->addSql('CREATE INDEX IDX_6BFE52B838248176 ON ssl_fee (currency_id)');
        $this->addSql('CREATE TABLE currency (id UUID NOT NULL, currency VARCHAR(4) NOT NULL, name VARCHAR(75) NOT NULL, symbol VARCHAR(4) NOT NULL, symbol_order BOOLEAN NOT NULL, symbol_space BOOLEAN NOT NULL, notes TEXT DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE timezone (id UUID NOT NULL, timezone VARCHAR(50) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE hosting (id UUID NOT NULL, creation_type_id UUID DEFAULT NULL, name VARCHAR(100) NOT NULL, url VARCHAR(100) DEFAULT NULL, notes TEXT DEFAULT NULL, created_by VARCHAR(255) DEFAULT NULL, updated_by VARCHAR(255) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_E9168FDAE54D5EF8 ON hosting (creation_type_id)');
        $this->addSql('CREATE TABLE ssl_provider (id UUID NOT NULL, creation_type_id UUID DEFAULT NULL, name VARCHAR(100) NOT NULL, url VARCHAR(100) DEFAULT NULL, notes TEXT DEFAULT NULL, created_by VARCHAR(255) DEFAULT NULL, updated_by VARCHAR(255) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_DE176735E54D5EF8 ON ssl_provider (creation_type_id)');
        $this->addSql('CREATE TABLE setting (id UUID NOT NULL, default_category_domains UUID DEFAULT NULL, default_category_ssl UUID DEFAULT NULL, default_dns UUID DEFAULT NULL, default_host UUID DEFAULT NULL, default_ip_address_domains UUID DEFAULT NULL, default_ip_address_ssl UUID DEFAULT NULL, default_owner_domains UUID DEFAULT NULL, default_owner_ssl UUID DEFAULT NULL, default_registrar UUID DEFAULT NULL, default_registrar_account UUID DEFAULT NULL, default_ssl_provider_account UUID DEFAULT NULL, default_ssl_type UUID DEFAULT NULL, default_ssl_provider UUID DEFAULT NULL, email_signature_id UUID DEFAULT NULL, full_url VARCHAR(100) DEFAULT \'\'\'http://\'\'\' NOT NULL, db_version VARCHAR(12) NOT NULL, upgrade_available BOOLEAN NOT NULL, email_address VARCHAR(100) NOT NULL, large_mode BOOLEAN NOT NULL, expiration_days INT DEFAULT 60 NOT NULL, currency_converter VARCHAR(10) DEFAULT \'\'\'era\'\'\' NOT NULL, use_smtp BOOLEAN NOT NULL, smtp_server VARCHAR(255) DEFAULT NULL, smtp_protocol VARCHAR(3) DEFAULT \'\'\'tls\'\'\', smtp_port VARCHAR(5) DEFAULT \'587\', smtp_email_address VARCHAR(100) DEFAULT NULL, smtp_username VARCHAR(100) DEFAULT NULL, smtp_password VARCHAR(255) DEFAULT NULL, debug_mode BOOLEAN NOT NULL, local_php_log BOOLEAN NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_9F74B898C45E37B4 ON setting (default_category_domains)');
        $this->addSql('CREATE INDEX IDX_9F74B898EEF440AD ON setting (default_category_ssl)');
        $this->addSql('CREATE INDEX IDX_9F74B898AC8AAF6C ON setting (default_dns)');
        $this->addSql('CREATE INDEX IDX_9F74B8988AD628FB ON setting (default_host)');
        $this->addSql('CREATE INDEX IDX_9F74B8983ADC3BD3 ON setting (default_ip_address_domains)');
        $this->addSql('CREATE INDEX IDX_9F74B8984A8A332B ON setting (default_ip_address_ssl)');
        $this->addSql('CREATE INDEX IDX_9F74B898362CA551 ON setting (default_owner_domains)');
        $this->addSql('CREATE INDEX IDX_9F74B898D7493EB0 ON setting (default_owner_ssl)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_9F74B8989F680E60 ON setting (default_registrar)');
        $this->addSql('CREATE INDEX IDX_9F74B8983E5B51C9 ON setting (default_registrar_account)');
        $this->addSql('CREATE INDEX IDX_9F74B898B7279A12 ON setting (default_ssl_provider_account)');
        $this->addSql('CREATE INDEX IDX_9F74B898F4D6ACEC ON setting (default_ssl_type)');
        $this->addSql('CREATE INDEX IDX_9F74B898FCC1829F ON setting (default_ssl_provider)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_9F74B898B872FE69 ON setting (email_signature_id)');
        $this->addSql('CREATE TABLE segment_data (id UUID NOT NULL, segment_id UUID DEFAULT NULL, domain VARCHAR(255) NOT NULL, active BOOLEAN NOT NULL, inactive BOOLEAN NOT NULL, missing BOOLEAN NOT NULL, filtered BOOLEAN NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_7250743EDB296AAD ON segment_data (segment_id)');
        $this->addSql('CREATE TABLE domain_queue_list (id UUID NOT NULL, api_registrar_id UUID DEFAULT NULL, owner_id UUID DEFAULT NULL, registrar_id UUID DEFAULT NULL, account_id UUID DEFAULT NULL, domain_count INT NOT NULL, processing BOOLEAN NOT NULL, ready_to_import BOOLEAN NOT NULL, finished BOOLEAN NOT NULL, copied_to_history BOOLEAN NOT NULL, created_by VARCHAR(255) DEFAULT NULL, updated_by VARCHAR(255) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_701AACABDBC0F66C ON domain_queue_list (api_registrar_id)');
        $this->addSql('CREATE INDEX IDX_701AACAB7E3C61F9 ON domain_queue_list (owner_id)');
        $this->addSql('CREATE INDEX IDX_701AACABD1AA2FC1 ON domain_queue_list (registrar_id)');
        $this->addSql('CREATE INDEX IDX_701AACAB9B6B5FBA ON domain_queue_list (account_id)');
        $this->addSql('CREATE TABLE domain_queue (id UUID NOT NULL, api_registrar_id UUID DEFAULT NULL, domain_id UUID DEFAULT NULL, owner_id UUID DEFAULT NULL, registrar_id UUID DEFAULT NULL, account_id UUID DEFAULT NULL, category_id UUID DEFAULT NULL, dns_id UUID DEFAULT NULL, ip_id UUID DEFAULT NULL, hosting_id UUID DEFAULT NULL, domain VARCHAR(255) NOT NULL, tld VARCHAR(50) NOT NULL, expiry_date DATE DEFAULT NULL, autorenew BOOLEAN NOT NULL, privacy BOOLEAN NOT NULL, processing BOOLEAN NOT NULL, ready_to_import BOOLEAN NOT NULL, finished BOOLEAN NOT NULL, already_in_domains BOOLEAN NOT NULL, already_in_queue BOOLEAN NOT NULL, invalid_domain BOOLEAN NOT NULL, copied_to_history BOOLEAN NOT NULL, created_by VARCHAR(255) DEFAULT NULL, updated_by VARCHAR(255) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_AC8657B5DBC0F66C ON domain_queue (api_registrar_id)');
        $this->addSql('CREATE INDEX IDX_AC8657B5115F0EE5 ON domain_queue (domain_id)');
        $this->addSql('CREATE INDEX IDX_AC8657B57E3C61F9 ON domain_queue (owner_id)');
        $this->addSql('CREATE INDEX IDX_AC8657B5D1AA2FC1 ON domain_queue (registrar_id)');
        $this->addSql('CREATE INDEX IDX_AC8657B59B6B5FBA ON domain_queue (account_id)');
        $this->addSql('CREATE INDEX IDX_AC8657B512469DE2 ON domain_queue (category_id)');
        $this->addSql('CREATE INDEX IDX_AC8657B5E42F3693 ON domain_queue (dns_id)');
        $this->addSql('CREATE INDEX IDX_AC8657B5A03F5E9F ON domain_queue (ip_id)');
        $this->addSql('CREATE INDEX IDX_AC8657B5AE9044EA ON domain_queue (hosting_id)');
        $this->addSql('ALTER TABLE domain ADD CONSTRAINT FK_A7A91E0B7E3C61F9 FOREIGN KEY (owner_id) REFERENCES owner (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE domain ADD CONSTRAINT FK_A7A91E0BD1AA2FC1 FOREIGN KEY (registrar_id) REFERENCES registrar (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE domain ADD CONSTRAINT FK_A7A91E0B9B6B5FBA FOREIGN KEY (account_id) REFERENCES registrar_account (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE domain ADD CONSTRAINT FK_A7A91E0B12469DE2 FOREIGN KEY (category_id) REFERENCES category (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE domain ADD CONSTRAINT FK_A7A91E0BAB45AECA FOREIGN KEY (fee_id) REFERENCES fee (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE domain ADD CONSTRAINT FK_A7A91E0BE42F3693 FOREIGN KEY (dns_id) REFERENCES dns (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE domain ADD CONSTRAINT FK_A7A91E0BA03F5E9F FOREIGN KEY (ip_id) REFERENCES ip_address (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE domain ADD CONSTRAINT FK_A7A91E0BAE9044EA FOREIGN KEY (hosting_id) REFERENCES hosting (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE domain ADD CONSTRAINT FK_A7A91E0BE54D5EF8 FOREIGN KEY (creation_type_id) REFERENCES creation_type (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE category ADD CONSTRAINT FK_64C19C1E54D5EF8 FOREIGN KEY (creation_type_id) REFERENCES creation_type (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE segment ADD CONSTRAINT FK_1881F565E54D5EF8 FOREIGN KEY (creation_type_id) REFERENCES creation_type (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE registrar_account ADD CONSTRAINT FK_CBDB68567E3C61F9 FOREIGN KEY (owner_id) REFERENCES owner (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE registrar_account ADD CONSTRAINT FK_CBDB6856D1AA2FC1 FOREIGN KEY (registrar_id) REFERENCES registrar (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE registrar_account ADD CONSTRAINT FK_CBDB685684AA0A4F FOREIGN KEY (api_ip_id) REFERENCES ip_address (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE registrar_account ADD CONSTRAINT FK_CBDB6856E54D5EF8 FOREIGN KEY (creation_type_id) REFERENCES creation_type (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE owner ADD CONSTRAINT FK_CF60E67CE54D5EF8 FOREIGN KEY (creation_type_id) REFERENCES creation_type (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE registrar ADD CONSTRAINT FK_E0A26C7DBC0F66C FOREIGN KEY (api_registrar_id) REFERENCES api_registrar (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE registrar ADD CONSTRAINT FK_E0A26C7E54D5EF8 FOREIGN KEY (creation_type_id) REFERENCES creation_type (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE dns ADD CONSTRAINT FK_82EDDC41E54D5EF8 FOREIGN KEY (creation_type_id) REFERENCES creation_type (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE domain_queue_history ADD CONSTRAINT FK_56A81B9EDBC0F66C FOREIGN KEY (api_registrar_id) REFERENCES api_registrar (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE domain_queue_history ADD CONSTRAINT FK_56A81B9E115F0EE5 FOREIGN KEY (domain_id) REFERENCES domain (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE domain_queue_history ADD CONSTRAINT FK_56A81B9E7E3C61F9 FOREIGN KEY (owner_id) REFERENCES owner (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE domain_queue_history ADD CONSTRAINT FK_56A81B9ED1AA2FC1 FOREIGN KEY (registrar_id) REFERENCES registrar (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE domain_queue_history ADD CONSTRAINT FK_56A81B9E9B6B5FBA FOREIGN KEY (account_id) REFERENCES registrar_account (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE domain_queue_history ADD CONSTRAINT FK_56A81B9E12469DE2 FOREIGN KEY (category_id) REFERENCES category (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE domain_queue_history ADD CONSTRAINT FK_56A81B9EE42F3693 FOREIGN KEY (dns_id) REFERENCES dns (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE domain_queue_history ADD CONSTRAINT FK_56A81B9E5F23F921 FOREIGN KEY (ip_address_id) REFERENCES ip_address (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE domain_queue_history ADD CONSTRAINT FK_56A81B9EAE9044EA FOREIGN KEY (hosting_id) REFERENCES hosting (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE fee ADD CONSTRAINT FK_964964B5D1AA2FC1 FOREIGN KEY (registrar_id) REFERENCES registrar (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE fee ADD CONSTRAINT FK_964964B538248176 FOREIGN KEY (currency_id) REFERENCES currency (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE user_setting ADD CONSTRAINT FK_C779A692A76ED395 FOREIGN KEY (user_id) REFERENCES users (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE user_setting ADD CONSTRAINT FK_C779A692B8C24FFF FOREIGN KEY (default_category_domains_id) REFERENCES category (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE user_setting ADD CONSTRAINT FK_C779A692FD4872ED FOREIGN KEY (default_category_ssl_id) REFERENCES category (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE user_setting ADD CONSTRAINT FK_C779A69237E3DC0 FOREIGN KEY (default_dns_id) REFERENCES dns (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE user_setting ADD CONSTRAINT FK_C779A692ED3D80C0 FOREIGN KEY (default_host_id) REFERENCES hosting (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE user_setting ADD CONSTRAINT FK_C779A6925A593FA4 FOREIGN KEY (default_ip_address_domains_id) REFERENCES ip_address (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE user_setting ADD CONSTRAINT FK_C779A692AB5F6375 FOREIGN KEY (default_ip_address_ssl_id) REFERENCES ip_address (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE user_setting ADD CONSTRAINT FK_C779A692EA97A5CE FOREIGN KEY (default_owner_domains_id) REFERENCES owner (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE user_setting ADD CONSTRAINT FK_C779A692EDDAD9BE FOREIGN KEY (default_owner_ssl_id) REFERENCES owner (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE user_setting ADD CONSTRAINT FK_C779A692F37CCA6B FOREIGN KEY (default_registrar_id) REFERENCES registrar (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE user_setting ADD CONSTRAINT FK_C779A692A7268CA8 FOREIGN KEY (default_registrar_account_id) REFERENCES registrar_account (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE user_setting ADD CONSTRAINT FK_C779A69257476562 FOREIGN KEY (default_ssl_provider_account_id) REFERENCES ssl_account (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE user_setting ADD CONSTRAINT FK_C779A692ABBB6804 FOREIGN KEY (default_ssl_type_id) REFERENCES ssl_cert_type (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE user_setting ADD CONSTRAINT FK_C779A69275D832EE FOREIGN KEY (default_ssl_provider_id) REFERENCES ssl_provider (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE ssl_account ADD CONSTRAINT FK_C732A1857E3C61F9 FOREIGN KEY (owner_id) REFERENCES owner (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE ssl_account ADD CONSTRAINT FK_C732A185ED8E9A32 FOREIGN KEY (ssl_provider_id) REFERENCES ssl_provider (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE ssl_account ADD CONSTRAINT FK_C732A185E54D5EF8 FOREIGN KEY (creation_type_id) REFERENCES creation_type (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE users ADD CONSTRAINT FK_1483A5E9E54D5EF8 FOREIGN KEY (creation_type_id) REFERENCES creation_type (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE ssl_cert ADD CONSTRAINT FK_72E6EBE07E3C61F9 FOREIGN KEY (owner_id) REFERENCES owner (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE ssl_cert ADD CONSTRAINT FK_72E6EBE0ED8E9A32 FOREIGN KEY (ssl_provider_id) REFERENCES ssl_provider (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE ssl_cert ADD CONSTRAINT FK_72E6EBE09B6B5FBA FOREIGN KEY (account_id) REFERENCES ssl_account (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE ssl_cert ADD CONSTRAINT FK_72E6EBE0115F0EE5 FOREIGN KEY (domain_id) REFERENCES domain (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE ssl_cert ADD CONSTRAINT FK_72E6EBE0C54C8C93 FOREIGN KEY (type_id) REFERENCES ssl_cert_type (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE ssl_cert ADD CONSTRAINT FK_72E6EBE0A03F5E9F FOREIGN KEY (ip_id) REFERENCES ip_address (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE ssl_cert ADD CONSTRAINT FK_72E6EBE012469DE2 FOREIGN KEY (category_id) REFERENCES category (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE ssl_cert ADD CONSTRAINT FK_72E6EBE0AB45AECA FOREIGN KEY (fee_id) REFERENCES ssl_fee (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE ssl_cert ADD CONSTRAINT FK_72E6EBE0E54D5EF8 FOREIGN KEY (creation_type_id) REFERENCES creation_type (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE ssl_cert_type ADD CONSTRAINT FK_483791B2E54D5EF8 FOREIGN KEY (creation_type_id) REFERENCES creation_type (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE domain_queue_list_history ADD CONSTRAINT FK_7F4112C4DBC0F66C FOREIGN KEY (api_registrar_id) REFERENCES api_registrar (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE domain_queue_list_history ADD CONSTRAINT FK_7F4112C47E3C61F9 FOREIGN KEY (owner_id) REFERENCES owner (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE domain_queue_list_history ADD CONSTRAINT FK_7F4112C4D1AA2FC1 FOREIGN KEY (registrar_id) REFERENCES registrar (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE domain_queue_list_history ADD CONSTRAINT FK_7F4112C49B6B5FBA FOREIGN KEY (account_id) REFERENCES registrar_account (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE ip_address ADD CONSTRAINT FK_22FFD58CE54D5EF8 FOREIGN KEY (creation_type_id) REFERENCES creation_type (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE ssl_fee ADD CONSTRAINT FK_6BFE52B8ED8E9A32 FOREIGN KEY (ssl_provider_id) REFERENCES ssl_provider (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE ssl_fee ADD CONSTRAINT FK_6BFE52B8C54C8C93 FOREIGN KEY (type_id) REFERENCES ssl_cert_type (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE ssl_fee ADD CONSTRAINT FK_6BFE52B838248176 FOREIGN KEY (currency_id) REFERENCES currency (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE hosting ADD CONSTRAINT FK_E9168FDAE54D5EF8 FOREIGN KEY (creation_type_id) REFERENCES creation_type (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE ssl_provider ADD CONSTRAINT FK_DE176735E54D5EF8 FOREIGN KEY (creation_type_id) REFERENCES creation_type (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE setting ADD CONSTRAINT FK_9F74B898C45E37B4 FOREIGN KEY (default_category_domains) REFERENCES category (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE setting ADD CONSTRAINT FK_9F74B898EEF440AD FOREIGN KEY (default_category_ssl) REFERENCES category (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE setting ADD CONSTRAINT FK_9F74B898AC8AAF6C FOREIGN KEY (default_dns) REFERENCES dns (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE setting ADD CONSTRAINT FK_9F74B8988AD628FB FOREIGN KEY (default_host) REFERENCES hosting (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE setting ADD CONSTRAINT FK_9F74B8983ADC3BD3 FOREIGN KEY (default_ip_address_domains) REFERENCES ip_address (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE setting ADD CONSTRAINT FK_9F74B8984A8A332B FOREIGN KEY (default_ip_address_ssl) REFERENCES ip_address (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE setting ADD CONSTRAINT FK_9F74B898362CA551 FOREIGN KEY (default_owner_domains) REFERENCES owner (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE setting ADD CONSTRAINT FK_9F74B898D7493EB0 FOREIGN KEY (default_owner_ssl) REFERENCES owner (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE setting ADD CONSTRAINT FK_9F74B8989F680E60 FOREIGN KEY (default_registrar) REFERENCES registrar (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE setting ADD CONSTRAINT FK_9F74B8983E5B51C9 FOREIGN KEY (default_registrar_account) REFERENCES registrar_account (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE setting ADD CONSTRAINT FK_9F74B898B7279A12 FOREIGN KEY (default_ssl_provider_account) REFERENCES ssl_account (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE setting ADD CONSTRAINT FK_9F74B898F4D6ACEC FOREIGN KEY (default_ssl_type) REFERENCES ssl_cert_type (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE setting ADD CONSTRAINT FK_9F74B898FCC1829F FOREIGN KEY (default_ssl_provider) REFERENCES ssl_provider (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE setting ADD CONSTRAINT FK_9F74B898B872FE69 FOREIGN KEY (email_signature_id) REFERENCES users (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE segment_data ADD CONSTRAINT FK_7250743EDB296AAD FOREIGN KEY (segment_id) REFERENCES segment (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE domain_queue_list ADD CONSTRAINT FK_701AACABDBC0F66C FOREIGN KEY (api_registrar_id) REFERENCES api_registrar (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE domain_queue_list ADD CONSTRAINT FK_701AACAB7E3C61F9 FOREIGN KEY (owner_id) REFERENCES owner (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE domain_queue_list ADD CONSTRAINT FK_701AACABD1AA2FC1 FOREIGN KEY (registrar_id) REFERENCES registrar (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE domain_queue_list ADD CONSTRAINT FK_701AACAB9B6B5FBA FOREIGN KEY (account_id) REFERENCES registrar_account (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE domain_queue ADD CONSTRAINT FK_AC8657B5DBC0F66C FOREIGN KEY (api_registrar_id) REFERENCES api_registrar (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE domain_queue ADD CONSTRAINT FK_AC8657B5115F0EE5 FOREIGN KEY (domain_id) REFERENCES domain (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE domain_queue ADD CONSTRAINT FK_AC8657B57E3C61F9 FOREIGN KEY (owner_id) REFERENCES owner (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE domain_queue ADD CONSTRAINT FK_AC8657B5D1AA2FC1 FOREIGN KEY (registrar_id) REFERENCES registrar (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE domain_queue ADD CONSTRAINT FK_AC8657B59B6B5FBA FOREIGN KEY (account_id) REFERENCES registrar_account (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE domain_queue ADD CONSTRAINT FK_AC8657B512469DE2 FOREIGN KEY (category_id) REFERENCES category (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE domain_queue ADD CONSTRAINT FK_AC8657B5E42F3693 FOREIGN KEY (dns_id) REFERENCES dns (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE domain_queue ADD CONSTRAINT FK_AC8657B5A03F5E9F FOREIGN KEY (ip_id) REFERENCES ip_address (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE domain_queue ADD CONSTRAINT FK_AC8657B5AE9044EA FOREIGN KEY (hosting_id) REFERENCES hosting (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
    }

    public function down(Schema $schema) : void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() !== 'postgresql', 'Migration can only be executed safely on \'postgresql\'.');

        $this->addSql('ALTER TABLE domain_queue_history DROP CONSTRAINT FK_56A81B9E115F0EE5');
        $this->addSql('ALTER TABLE ssl_cert DROP CONSTRAINT FK_72E6EBE0115F0EE5');
        $this->addSql('ALTER TABLE domain_queue DROP CONSTRAINT FK_AC8657B5115F0EE5');
        $this->addSql('ALTER TABLE domain DROP CONSTRAINT FK_A7A91E0B12469DE2');
        $this->addSql('ALTER TABLE domain_queue_history DROP CONSTRAINT FK_56A81B9E12469DE2');
        $this->addSql('ALTER TABLE user_setting DROP CONSTRAINT FK_C779A692B8C24FFF');
        $this->addSql('ALTER TABLE user_setting DROP CONSTRAINT FK_C779A692FD4872ED');
        $this->addSql('ALTER TABLE ssl_cert DROP CONSTRAINT FK_72E6EBE012469DE2');
        $this->addSql('ALTER TABLE setting DROP CONSTRAINT FK_9F74B898C45E37B4');
        $this->addSql('ALTER TABLE setting DROP CONSTRAINT FK_9F74B898EEF440AD');
        $this->addSql('ALTER TABLE domain_queue DROP CONSTRAINT FK_AC8657B512469DE2');
        $this->addSql('ALTER TABLE segment_data DROP CONSTRAINT FK_7250743EDB296AAD');
        $this->addSql('ALTER TABLE domain DROP CONSTRAINT FK_A7A91E0B9B6B5FBA');
        $this->addSql('ALTER TABLE domain_queue_history DROP CONSTRAINT FK_56A81B9E9B6B5FBA');
        $this->addSql('ALTER TABLE user_setting DROP CONSTRAINT FK_C779A692A7268CA8');
        $this->addSql('ALTER TABLE domain_queue_list_history DROP CONSTRAINT FK_7F4112C49B6B5FBA');
        $this->addSql('ALTER TABLE setting DROP CONSTRAINT FK_9F74B8983E5B51C9');
        $this->addSql('ALTER TABLE domain_queue_list DROP CONSTRAINT FK_701AACAB9B6B5FBA');
        $this->addSql('ALTER TABLE domain_queue DROP CONSTRAINT FK_AC8657B59B6B5FBA');
        $this->addSql('ALTER TABLE domain DROP CONSTRAINT FK_A7A91E0B7E3C61F9');
        $this->addSql('ALTER TABLE registrar_account DROP CONSTRAINT FK_CBDB68567E3C61F9');
        $this->addSql('ALTER TABLE domain_queue_history DROP CONSTRAINT FK_56A81B9E7E3C61F9');
        $this->addSql('ALTER TABLE user_setting DROP CONSTRAINT FK_C779A692EA97A5CE');
        $this->addSql('ALTER TABLE user_setting DROP CONSTRAINT FK_C779A692EDDAD9BE');
        $this->addSql('ALTER TABLE ssl_account DROP CONSTRAINT FK_C732A1857E3C61F9');
        $this->addSql('ALTER TABLE ssl_cert DROP CONSTRAINT FK_72E6EBE07E3C61F9');
        $this->addSql('ALTER TABLE domain_queue_list_history DROP CONSTRAINT FK_7F4112C47E3C61F9');
        $this->addSql('ALTER TABLE setting DROP CONSTRAINT FK_9F74B898362CA551');
        $this->addSql('ALTER TABLE setting DROP CONSTRAINT FK_9F74B898D7493EB0');
        $this->addSql('ALTER TABLE domain_queue_list DROP CONSTRAINT FK_701AACAB7E3C61F9');
        $this->addSql('ALTER TABLE domain_queue DROP CONSTRAINT FK_AC8657B57E3C61F9');
        $this->addSql('ALTER TABLE domain DROP CONSTRAINT FK_A7A91E0BD1AA2FC1');
        $this->addSql('ALTER TABLE registrar_account DROP CONSTRAINT FK_CBDB6856D1AA2FC1');
        $this->addSql('ALTER TABLE domain_queue_history DROP CONSTRAINT FK_56A81B9ED1AA2FC1');
        $this->addSql('ALTER TABLE fee DROP CONSTRAINT FK_964964B5D1AA2FC1');
        $this->addSql('ALTER TABLE user_setting DROP CONSTRAINT FK_C779A692F37CCA6B');
        $this->addSql('ALTER TABLE domain_queue_list_history DROP CONSTRAINT FK_7F4112C4D1AA2FC1');
        $this->addSql('ALTER TABLE setting DROP CONSTRAINT FK_9F74B8989F680E60');
        $this->addSql('ALTER TABLE domain_queue_list DROP CONSTRAINT FK_701AACABD1AA2FC1');
        $this->addSql('ALTER TABLE domain_queue DROP CONSTRAINT FK_AC8657B5D1AA2FC1');
        $this->addSql('ALTER TABLE domain DROP CONSTRAINT FK_A7A91E0BE42F3693');
        $this->addSql('ALTER TABLE domain_queue_history DROP CONSTRAINT FK_56A81B9EE42F3693');
        $this->addSql('ALTER TABLE user_setting DROP CONSTRAINT FK_C779A69237E3DC0');
        $this->addSql('ALTER TABLE setting DROP CONSTRAINT FK_9F74B898AC8AAF6C');
        $this->addSql('ALTER TABLE domain_queue DROP CONSTRAINT FK_AC8657B5E42F3693');
        $this->addSql('ALTER TABLE domain DROP CONSTRAINT FK_A7A91E0BAB45AECA');
        $this->addSql('ALTER TABLE domain DROP CONSTRAINT FK_A7A91E0BE54D5EF8');
        $this->addSql('ALTER TABLE category DROP CONSTRAINT FK_64C19C1E54D5EF8');
        $this->addSql('ALTER TABLE segment DROP CONSTRAINT FK_1881F565E54D5EF8');
        $this->addSql('ALTER TABLE registrar_account DROP CONSTRAINT FK_CBDB6856E54D5EF8');
        $this->addSql('ALTER TABLE owner DROP CONSTRAINT FK_CF60E67CE54D5EF8');
        $this->addSql('ALTER TABLE registrar DROP CONSTRAINT FK_E0A26C7E54D5EF8');
        $this->addSql('ALTER TABLE dns DROP CONSTRAINT FK_82EDDC41E54D5EF8');
        $this->addSql('ALTER TABLE ssl_account DROP CONSTRAINT FK_C732A185E54D5EF8');
        $this->addSql('ALTER TABLE users DROP CONSTRAINT FK_1483A5E9E54D5EF8');
        $this->addSql('ALTER TABLE ssl_cert DROP CONSTRAINT FK_72E6EBE0E54D5EF8');
        $this->addSql('ALTER TABLE ssl_cert_type DROP CONSTRAINT FK_483791B2E54D5EF8');
        $this->addSql('ALTER TABLE ip_address DROP CONSTRAINT FK_22FFD58CE54D5EF8');
        $this->addSql('ALTER TABLE hosting DROP CONSTRAINT FK_E9168FDAE54D5EF8');
        $this->addSql('ALTER TABLE ssl_provider DROP CONSTRAINT FK_DE176735E54D5EF8');
        $this->addSql('ALTER TABLE registrar DROP CONSTRAINT FK_E0A26C7DBC0F66C');
        $this->addSql('ALTER TABLE domain_queue_history DROP CONSTRAINT FK_56A81B9EDBC0F66C');
        $this->addSql('ALTER TABLE domain_queue_list_history DROP CONSTRAINT FK_7F4112C4DBC0F66C');
        $this->addSql('ALTER TABLE domain_queue_list DROP CONSTRAINT FK_701AACABDBC0F66C');
        $this->addSql('ALTER TABLE domain_queue DROP CONSTRAINT FK_AC8657B5DBC0F66C');
        $this->addSql('ALTER TABLE user_setting DROP CONSTRAINT FK_C779A69257476562');
        $this->addSql('ALTER TABLE ssl_cert DROP CONSTRAINT FK_72E6EBE09B6B5FBA');
        $this->addSql('ALTER TABLE setting DROP CONSTRAINT FK_9F74B898B7279A12');
        $this->addSql('ALTER TABLE user_setting DROP CONSTRAINT FK_C779A692A76ED395');
        $this->addSql('ALTER TABLE setting DROP CONSTRAINT FK_9F74B898B872FE69');
        $this->addSql('ALTER TABLE user_setting DROP CONSTRAINT FK_C779A692ABBB6804');
        $this->addSql('ALTER TABLE ssl_cert DROP CONSTRAINT FK_72E6EBE0C54C8C93');
        $this->addSql('ALTER TABLE ssl_fee DROP CONSTRAINT FK_6BFE52B8C54C8C93');
        $this->addSql('ALTER TABLE setting DROP CONSTRAINT FK_9F74B898F4D6ACEC');
        $this->addSql('ALTER TABLE domain DROP CONSTRAINT FK_A7A91E0BA03F5E9F');
        $this->addSql('ALTER TABLE registrar_account DROP CONSTRAINT FK_CBDB685684AA0A4F');
        $this->addSql('ALTER TABLE domain_queue_history DROP CONSTRAINT FK_56A81B9E5F23F921');
        $this->addSql('ALTER TABLE user_setting DROP CONSTRAINT FK_C779A6925A593FA4');
        $this->addSql('ALTER TABLE user_setting DROP CONSTRAINT FK_C779A692AB5F6375');
        $this->addSql('ALTER TABLE ssl_cert DROP CONSTRAINT FK_72E6EBE0A03F5E9F');
        $this->addSql('ALTER TABLE setting DROP CONSTRAINT FK_9F74B8983ADC3BD3');
        $this->addSql('ALTER TABLE setting DROP CONSTRAINT FK_9F74B8984A8A332B');
        $this->addSql('ALTER TABLE domain_queue DROP CONSTRAINT FK_AC8657B5A03F5E9F');
        $this->addSql('ALTER TABLE ssl_cert DROP CONSTRAINT FK_72E6EBE0AB45AECA');
        $this->addSql('ALTER TABLE fee DROP CONSTRAINT FK_964964B538248176');
        $this->addSql('ALTER TABLE ssl_fee DROP CONSTRAINT FK_6BFE52B838248176');
        $this->addSql('ALTER TABLE domain DROP CONSTRAINT FK_A7A91E0BAE9044EA');
        $this->addSql('ALTER TABLE domain_queue_history DROP CONSTRAINT FK_56A81B9EAE9044EA');
        $this->addSql('ALTER TABLE user_setting DROP CONSTRAINT FK_C779A692ED3D80C0');
        $this->addSql('ALTER TABLE setting DROP CONSTRAINT FK_9F74B8988AD628FB');
        $this->addSql('ALTER TABLE domain_queue DROP CONSTRAINT FK_AC8657B5AE9044EA');
        $this->addSql('ALTER TABLE user_setting DROP CONSTRAINT FK_C779A69275D832EE');
        $this->addSql('ALTER TABLE ssl_account DROP CONSTRAINT FK_C732A185ED8E9A32');
        $this->addSql('ALTER TABLE ssl_cert DROP CONSTRAINT FK_72E6EBE0ED8E9A32');
        $this->addSql('ALTER TABLE ssl_fee DROP CONSTRAINT FK_6BFE52B8ED8E9A32');
        $this->addSql('ALTER TABLE setting DROP CONSTRAINT FK_9F74B898FCC1829F');
        $this->addSql('DROP TABLE domain');
        $this->addSql('DROP TABLE category');
        $this->addSql('DROP TABLE segment');
        $this->addSql('DROP TABLE registrar_account');
        $this->addSql('DROP TABLE owner');
        $this->addSql('DROP TABLE registrar');
        $this->addSql('DROP TABLE dns');
        $this->addSql('DROP TABLE domain_queue_history');
        $this->addSql('DROP TABLE custom_field_type');
        $this->addSql('DROP TABLE fee');
        $this->addSql('DROP TABLE user_setting');
        $this->addSql('DROP TABLE creation_type');
        $this->addSql('DROP TABLE api_registrar');
        $this->addSql('DROP TABLE ssl_account');
        $this->addSql('DROP TABLE users');
        $this->addSql('DROP TABLE ssl_cert');
        $this->addSql('DROP TABLE ssl_cert_type');
        $this->addSql('DROP TABLE domain_queue_list_history');
        $this->addSql('DROP TABLE ip_address');
        $this->addSql('DROP TABLE scheduler');
        $this->addSql('DROP TABLE ssl_fee');
        $this->addSql('DROP TABLE currency');
        $this->addSql('DROP TABLE timezone');
        $this->addSql('DROP TABLE hosting');
        $this->addSql('DROP TABLE ssl_provider');
        $this->addSql('DROP TABLE setting');
        $this->addSql('DROP TABLE segment_data');
        $this->addSql('DROP TABLE domain_queue_list');
        $this->addSql('DROP TABLE domain_queue');
    }
}
